Chapter04/PIOLightningComponents/src/objects/PredictionIOSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>API_Endpoint__c</fullName>
        <description>Endpoint for the API</description>
        <label>API Endpoint</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ApplicationID__c</fullName>
        <description>ApplicationID of the PredictionIO Event Server or Engine</description>
        <inlineHelpText>ApplicationID of the PredictionIO Event Server or Engine</inlineHelpText>
        <label>ApplicationID</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>PredictionIOSettings</label>
</CustomObject>

Chapter04/PIOLightningComponents/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PredictionIOExternalId__c</fullName>
        <externalId>true</externalId>
        <label>PredictionIOExternalId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

Chapter04/PIOLightningComponents/src/classes/TestProductViewCaptureController.cls
@isTest
private class TestProductViewCaptureController{

    static testmethod void testcallEventServer(){
        Product2 product = new Product2();
        product.Name = 'Test PIO Product';
        product.Family = 'PIO Family';
        product.ProductCode = 'PIOCODE';
        product.PredictionIOExternalId__c = 'i1';
        insert product;
         //Insert the Custom Setting For PredictionIO EventServer
        PredictionIOSettings__c pioEventServer = new PredictionIOSettings__c();
        pioEventServer.Name = 'PredictionIOEventServer';
        pioEventServer.API_Endpoint__c = 'https://predictionioserver.herokuapp.com/events.json';
        pioEventServer.ApplicationID__c = '123';
        insert pioEventServer;
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockPredictionIOEventServerResponse());
        Test.StartTest();
            ProductViewCaptureController.callEventServer(product.Id);
        Test.StopTest();
    }

}