Chapter04/PIOLightningComponents/src/objects/PredictionIOSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>API_Endpoint__c</fullName>
        <description>Endpoint for the API</description>
        <label>API Endpoint</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>PredictionIOSettings</label>
</CustomObject>

Chapter04/PIOLightningComponents/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PredictionIOExternalId__c</fullName>
        <externalId>true</externalId>
        <label>PredictionIOExternalId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

Chapter04/PIOLightningComponents/src/classes/SimilarProductRecommenderController.cls
public class SimilarProductRecommenderController {

    @AuraEnabled
    public static list<Product2> queryPredictionAPI(String productId){
        list<Product2> lstProducts = new list<Product2>();
         try{
            PredictionIOSettings__c pioEngineSettings = PredictionIOSettings__c.getValues('PredictionIOEngine');
            String item = ProductSelector.getProduct(productId).PredictionIOExternalId__c;
            list<String> items = new list<String>();
            items.add(item);
            //Form Predictor RequestBody
            SimilarProductRecommenderModel productPredictor = new  SimilarProductRecommenderModel();
            productPredictor.items = items;
            productPredictor.num = 4;
            String requestBody = JSON.serialize(productPredictor);
            HttpUtil http = new HttpUtil();
            HttpResponse response = http.invokePostRequest(pioEngineSettings.API_Endpoint__c,requestBody);
            system.debug('RESPONSE..'+response.getBody());
            if(response.getStatusCode() == 200){
             PredictionIOResult result = (PredictionIOResult) System.JSON.deserialize(response.getBody(), PredictionIOResult.class);
             set<String> similarProductIds = new  set<String>();
             for(PredictionIOResult.cls_itemScores pioitem :result.itemScores){
                similarProductIds.add(pioitem.item);
             }
             lstProducts = ProductSelector.getProducts(similarProductIds);
            }else{
                throw new AuraHandledException('Engine is Down...Restart the PredictionIO Engine'); 
            }
         }catch(exception e){
            throw new AuraHandledException(e.getmessage()); 
        }
        return lstProducts;
    }

}