Chapter04/PIOLightningComponents/src/objects/PredictionIOSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>API_Endpoint__c</fullName>
        <description>Endpoint for the API</description>
        <label>API Endpoint</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ApplicationID__c</fullName>
        <description>ApplicationID of the PredictionIO Event Server or Engine</description>
        <inlineHelpText>ApplicationID of the PredictionIO Event Server or Engine</inlineHelpText>
        <label>ApplicationID</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>PredictionIOSettings</label>
</CustomObject>

Chapter4/PIOLightningComponents/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PredictionIOExternalId__c</fullName>
        <description>This is an externalId on User for PredictionIO API</description>
        <externalId>true</externalId>
        <inlineHelpText>This is an externalId on User for PredictionIO API</inlineHelpText>
        <label>PredictionIOExternalId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

Chapter04/PIOLightningComponents/src/classes/ProductViewCaptureController.cls
public with sharing class ProductViewCaptureController {

     /**
    * Makes an API call to PredictionIO Event Server To Capture Product View Event
    * @param    Id of the Product
    * @throws   AuraEnabled Exception if something fails
    */ 
    @AuraEnabled
    public static void callEventServer(String productId){
        if(productId == null){
            throw new AuraHandledException('ProductId is missing..'); 
        }
        try{
            PredictionIOSettings__c pioSettings = PredictionIOSettings__c.getValues('PredictionIOEventServer'); 
            String endPoint = pioSettings.API_Endpoint__c + '?accessKey=' + pioSettings.ApplicationID__c;
            String pioproductId = ProductSelector.getProduct(productId).PredictionIOExternalId__c;
            String piouserId = UserSelector.getCurrentUser().PredictionIOExternalId__c;
            ProductViewCaptureModel productviewEvent = new ProductViewCaptureModel('view','user',piouserId,'item',pioproductId);
            String requestBody = JSON.serialize(productviewEvent);
            HttpUtil http = new HttpUtil();
            HttpResponse response = http.invokePostRequest(endPoint,requestBody);
            if(response.getStatusCode() != 201){
                throw new AuraHandledException('Free Dyno is Sleeping ...Start the server'); 
            }
        }catch(exception e){
            throw new AuraHandledException(e.getmessage()); 
        }
       
    }

   
}