Chapter04/PIOLightningComponents/src/objects/PredictionIOSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>API_Endpoint__c</fullName>
        <description>Endpoint for the API</description>
        <label>API Endpoint</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ApplicationID__c</fullName>
        <description>ApplicationID of the PredictionIO Event Server or Engine</description>
        <inlineHelpText>ApplicationID of the PredictionIO Event Server or Engine</inlineHelpText>
        <label>ApplicationID</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>PredictionIOSettings</label>
</CustomObject>

Chapter04/PIOLightningComponents/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PredictionIOExternalId__c</fullName>
        <externalId>true</externalId>
        <label>PredictionIOExternalId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

Chapter04/PIOLightningComponents/src/classes/TestSimilarProductRecommenderController.cls
@isTest
private class TestSimilarProductRecommenderController{

     static testmethod void queryPredictionAPI(){
        list<Product2> lstProducts = new  list<Product2>();
        for(Integer i=1 ; i<6 ;i++){
            Product2 product = new Product2();
            product.Name = 'Test PIO Product' + i;
            product.Family = 'PIO Family' + i;
            product.ProductCode = 'PIOCODE' + i;
            product.PredictionIOExternalId__c = 'i'+i;
            lstProducts.add(product);
        }
        insert lstProducts;
         //Insert the Custom Setting For PredictionIO EventServer
        PredictionIOSettings__c pioEventServer = new PredictionIOSettings__c();
        pioEventServer.Name = 'PredictionIOEngine';
        pioEventServer.API_Endpoint__c = 'https://nameless-spire-13670.herokuapp.com/queries.json';
        pioEventServer.ApplicationID__c = '123';
        insert pioEventServer;
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockPredictionIOEngineResponse());
        Test.StartTest();
            list<Product2> lstProduct = SimilarProductRecommenderController.queryPredictionAPI(lstProducts[0].Id);
            system.assertEquals(lstProduct.size(),2);
        Test.StopTest();
    }

}