Chapter6/SalesforceEinsteinVision/src/objects/Einstein_Vision_Dataset__c.object
<CustomObject>
    <fields>
        <fullName>DatasetId__c</fullName>
        <description>Id of the Dataset</description>
        <inlineHelpText>Id of the Dataset</inlineHelpText>
        <label>DatasetId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModelId__c</fullName>
        <label>ModelId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Public_URL__c</fullName>
        <description>This holds the zip file public url used for creating datasets and training the model</description>
        <inlineHelpText>This holds the zip file public url used for creating datasets and training the model</inlineHelpText>
        <label>Public URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Training_Status__c</fullName>
        <description>This shows the Status of the training</description>
        <label>Training Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RUNNING</fullName>
                </value>
                <value>
                    <fullName>SUCCEEDED</fullName>
                </value>
                <value>
                    <fullName>FAILED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Einstein Vision Dataset</label>
    <nameField>
        <label>Einstein Vision Dataset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datasets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter06/SalesforceEinsteinVision/src/objects/Error_Log__c.object
<CustomObject>
    <description>This shows the Error log</description>
    <fields>
        <fullName>Einstein_Vision_Dataset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Einstein Vision Dataset</label>
        <referenceTo>Einstein_Vision_Dataset__c</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter06/SalesforceEinsteinVision/src/classes/EinsteinVisionGetTrainingStatusScheduler.cls
public with sharing class EinsteinVisionGetTrainingStatusScheduler implements Schedulable , Database.AllowsCallouts{
   
   public String modelId ;
   
   public EinsteinVisionGetTrainingStatusScheduler(String modelId){
     this.modelId = modelId;
   }
   
   public void execute(SchedulableContext SC) {
     getDatasetTrainJobStatus(modelId);
   }

   @future(callout=true)
   private static void getDatasetTrainJobStatus(String modelId){
    list<Error_Log__c> lsterrorlogs = new list<Error_Log__c>();
     //Create a new Instance of Dataset record
     Einstein_Vision_Dataset__c datasetToUpdate = new Einstein_Vision_Dataset__c();
     list<Einstein_Vision_Dataset__c> lstDatasetVision = [Select Id,Public_URL__c,ModelId__c,Training_Status__c,DatasetId__c from Einstein_Vision_Dataset__c where  ModelId__c =: modelId];
     if(lstDatasetVision.size()>0){
        Einstein_Vision_Dataset__c dataset = lstDatasetVision[0];
        datasetToUpdate.id = lstDatasetVision[0].id;
        EinsteinVisionTrainDataSetResponse einsteinTrainingResult = EinsteinVisionTrainDataset.gettrainingStatus(modelId,false);
        if(einsteinTrainingResult.status == 'SUCCEEDED'){
          datasetToUpdate.Training_Status__c = einsteinTrainingResult.status;
          update datasetToUpdate;
        }else if(einsteinTrainingResult.status == 'FAILED'){
            lsterrorlogs.add(EinsteinVisionUtility.logError('TRAINING','FAILED',dataset.Id));
            datasetToUpdate.Training_Status__c = einsteinTrainingResult.status;
            update datasetToUpdate;
            insert lsterrorlogs;
        }else{
            //Schedule the same job again after couple minutes
            System.schedule('DatasetTrainStatusJob'+System.now(), '0 '+DateTime.now().addMinutes(5).minute()+' */1 ? * *', new EinsteinVisionGetTrainingStatusScheduler(modelId));
        }
      }
   }

   
}