Chapter6/SalesforceEinsteinVision/src/objects/Einstein_Vision_Dataset__c.object
<CustomObject>
    <fields>
        <fullName>DatasetId__c</fullName>
        <description>Id of the Dataset</description>
        <inlineHelpText>Id of the Dataset</inlineHelpText>
        <label>DatasetId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Public_URL__c</fullName>
        <description>This holds the zip file public url used for creating datasets and training the model</description>
        <inlineHelpText>This holds the zip file public url used for creating datasets and training the model</inlineHelpText>
        <label>Public URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This holds the status of the dataset creation</description>
        <inlineHelpText>This holds the status of the dataset creation</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAILURE</fullName>
                </value>
                <value>
                    <fullName>SUCCEEDED</fullName>
                </value>
                <value>
                    <fullName>STARTED</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Einstein Vision Dataset</label>
    <nameField>
        <label>Einstein Vision Dataset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datasets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter06/SalesforceEinsteinVision/src/objects/Error_Log__c.object
<CustomObject>
    <description>This shows the Error log</description>
    <fields>
        <fullName>Einstein_Vision_Dataset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Einstein Vision Dataset</label>
        <referenceTo>Einstein_Vision_Dataset__c</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter06/SalesforceEinsteinVision/src/classes/EinsteinVisionGetStatusScheduler.cls
public with sharing class EinsteinVisionGetStatusScheduler implements Schedulable , Database.AllowsCallouts{
   
   public String datasetId ;
   
   public EinsteinVisionGetStatusScheduler(String datasetId){
     this.datasetId = datasetId;
   }
   
   public void execute(SchedulableContext SC) {
      getDatasetCreateStatus(datasetId);
   }

   @future(callout=true)
   private static void getDatasetCreateStatus(String datasetId){
    list<Error_Log__c> lsterrorlogs = new list<Error_Log__c>();
     //Create a new Instance of Dataset record
     Einstein_Vision_Dataset__c datasetToUpdate = new Einstein_Vision_Dataset__c();
     list<Einstein_Vision_Dataset__c> lstDatasetVision = [Select Id,Public_URL__c,DatasetId__c from Einstein_Vision_Dataset__c where DatasetId__c =:datasetId];
     if(lstDatasetVision.size()>0){
        Einstein_Vision_Dataset__c dataset = lstDatasetVision[0];
        datasetToUpdate.id = lstDatasetVision[0].id;
        EinsteinVisionDatasetResult einsteinResult = EinsteinVisionGetDataset.getDataSetStatus(datasetId,false);
        if(einsteinResult.statusMsg == 'SUCCEEDED'){
            datasetToUpdate.Status__c = einsteinResult.statusMsg;
            update datasetToUpdate;
            System.schedule('TrainDataset', '0 '+DateTime.now().addMinutes(5).minute()+' */1 ? * *', new EinsteinVisionTrainDatasetScheduler(datasetId));
        }else if(einsteinResult.statusMsg == 'FAILED'){
            lsterrorlogs.add(EinsteinVisionUtility.logError('DATASET CREATION','FAILED',dataset.Id));
            datasetToUpdate.Status__c = einsteinResult.statusMsg;
            update datasetToUpdate;
            insert lsterrorlogs;
        }else{
            //Schedule the same job again after couple minutes
            System.schedule('DatasetCreateStatusJob'+System.now(), '0 '+DateTime.now().addMinutes(2).minute()+' */1 ? * *', new EinsteinVisionGetStatusScheduler(string.valueof(einsteinResult.id)));
        }
     }
   }
}