Chapter6/SalesforceEinsteinVision/src/objects/Einstein_Vision_Dataset__c.object
<CustomObject>
    <fields>
        <fullName>DatasetId__c</fullName>
        <description>Id of the Dataset</description>
        <inlineHelpText>Id of the Dataset</inlineHelpText>
        <label>DatasetId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModelId__c</fullName>
        <label>ModelId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Public_URL__c</fullName>
        <description>This holds the zip file public url used for creating datasets and training the model</description>
        <inlineHelpText>This holds the zip file public url used for creating datasets and training the model</inlineHelpText>
        <label>Public URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Einstein Vision Dataset</label>
    <nameField>
        <label>Einstein Vision Dataset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datasets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter06/SalesforceEinsteinVision/src/objects/Error_Log__c.object
<CustomObject>
    <description>This shows the Error log</description>
    <fields>
        <fullName>Einstein_Vision_Dataset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Einstein Vision Dataset</label>
        <referenceTo>Einstein_Vision_Dataset__c</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter6/SalesforceEinsteinVision/src/classes/EinsteinVisionTrainDatasetScheduler.cls
public with sharing class EinsteinVisionTrainDatasetScheduler implements Schedulable , Database.AllowsCallouts{
   
   public String datasetId ;
   
   public EinsteinVisionTrainDatasetScheduler(String datasetId){
     this.datasetId = datasetId;
   }
   
   public void execute(SchedulableContext SC) {
     trainDataset(datasetId);
   }

   @future(callout=true)
   private static void trainDataset(String datasetId){
    list<Error_Log__c> lsterrorlogs = new list<Error_Log__c>();
     //Create a new Instance of Dataset record
     Einstein_Vision_Dataset__c datasetToUpdate = new Einstein_Vision_Dataset__c();
     list<Einstein_Vision_Dataset__c> lstDatasetVision = [Select Id,Name,Public_URL__c,DatasetId__c,ModelId__c from Einstein_Vision_Dataset__c where DatasetId__c =:datasetId];
     if(lstDatasetVision.size()>0){
        Einstein_Vision_Dataset__c dataset = lstDatasetVision[0];
        //train the Dataset
        try{
            EinsteinVisionTrainDataSetResponse response = EinsteinVisionTrainDataset.trainDataSet(dataset.name,datasetId,false);
            datasetToUpdate.Id = dataset.Id;
            String modelId = response.modelId;
            datasetToUpdate.ModelId__c = modelId;
            update datasetToUpdate;
             //Schedule the Job to start polling Einstein API for status of upload
            System.schedule('DatasetTrainStatusJob', '0 '+DateTime.now().addMinutes(2).minute()+' */1 ? * *', new EinsteinVisionGetTrainingStatusScheduler(modelId));
        }catch(exception e){
           lsterrorlogs.add(EinsteinVisionUtility.logError('TRAINING',e.getMessage(),dataset.id));
           insert lsterrorlogs;
        }
     }
   }
}