Chapter6/SalesforceEinsteinVision/src/objects/Einstein_Vision_Dataset__c.object
<CustomObject>
    <fields>
        <fullName>DatasetId__c</fullName>
        <description>Id of the Dataset</description>
        <inlineHelpText>Id of the Dataset</inlineHelpText>
        <label>DatasetId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Public_URL__c</fullName>
        <description>This holds the zip file public url used for creating datasets and training the model</description>
        <inlineHelpText>This holds the zip file public url used for creating datasets and training the model</inlineHelpText>
        <label>Public URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Einstein Vision Dataset</label>
    <nameField>
        <label>Einstein Vision Dataset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datasets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter06/SalesforceEinsteinVision/src/objects/Error_Log__c.object
<CustomObject>
    <description>This shows the Error log</description>
    <fields>
        <fullName>Einstein_Vision_Dataset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Einstein Vision Dataset</label>
        <referenceTo>Einstein_Vision_Dataset__c</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter6/SalesforceEinsteinVision/src/classes/EinsteinVisionCreateDatasetScheduler.cls
public with sharing class EinsteinVisionCreateDatasetScheduler implements Schedulable {

   private Id recordId ;

   public EinsteinVisionCreateDatasetScheduler(Id recordId){
      this.recordId = recordId;
   }
   
   public void execute(SchedulableContext sc) {
     createDataset(recordId);
   }
   
   @future(callout=true)
   private static void createDataset(Id recordId){
    list<Error_Log__c> lsterrorlogs = new list<Error_Log__c>();
     //Create a new Instance of Dataset record
     Einstein_Vision_Dataset__c datasetToUpdate = new Einstein_Vision_Dataset__c();
     list<Einstein_Vision_Dataset__c> lstDatasetVision = [Select Id,Public_URL__c,DatasetId__c from Einstein_Vision_Dataset__c where Id =:recordId];
     if(lstDatasetVision.size()>0){
        Einstein_Vision_Dataset__c dataset = lstDatasetVision[0];
         try{
            EinsteinVisionDatasetResult einsteinResult = EinstieinVisionCreateDatasetUtil.createDatasetFromURLAsync(dataset.Public_URL__c,false);
            datasetToUpdate.Id = recordId;
            datasetToUpdate.DatasetId__c = string.valueof(einsteinResult.id);
            update datasetToUpdate;
            //Schedule the Job to start polling Einstein API for status of upload
            System.schedule('DatasetCreateStatusJob', '0 '+DateTime.now().addMinutes(2).minute()+' */1 ? * *', new EinsteinVisionGetStatusScheduler(string.valueof(einsteinResult.id)));
        }catch(exception ex){
           lsterrorlogs.add(EinsteinVisionUtility.logError('DATASET CREATION',ex.getMessage(),dataset.id));
           insert lsterrorlogs;
        }
     }
   }
   
}