Chapter6/SalesforceEinsteinVision/src/objects/Einstein_Vision_Dataset__c.object
<CustomObject>
    <fields>
        <fullName>DatasetId__c</fullName>
        <description>Id of the Dataset</description>
        <inlineHelpText>Id of the Dataset</inlineHelpText>
        <label>DatasetId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModelId__c</fullName>
        <label>ModelId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Public_URL__c</fullName>
        <description>This holds the zip file public url used for creating datasets and training the model</description>
        <inlineHelpText>This holds the zip file public url used for creating datasets and training the model</inlineHelpText>
        <label>Public URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This holds the status of the dataset creation</description>
        <inlineHelpText>This holds the status of the dataset creation</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAILURE</fullName>
                </value>
                <value>
                    <fullName>SUCCEEDED</fullName>
                </value>
                <value>
                    <fullName>STARTED</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Training_Status__c</fullName>
        <description>This shows the Status of the training</description>
        <label>Training Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RUNNING</fullName>
                </value>
                <value>
                    <fullName>SUCCEEDED</fullName>
                </value>
                <value>
                    <fullName>FAILED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Einstein Vision Dataset</label>
    <nameField>
        <label>Einstein Vision Dataset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datasets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter06/SalesforceEinsteinVision/src/objects/Error_Log__c.object
<CustomObject>
    <description>This shows the Error log</description>
    <fields>
        <fullName>Einstein_Vision_Dataset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Einstein Vision Dataset</label>
        <referenceTo>Einstein_Vision_Dataset__c</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DATASET CREATION</fullName>
                </value>
                <value>
                    <fullName>TRAINING</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter06/SalesforceEinsteinVision/src/classes/EinsteinVisionQueueble.cls
public with sharing class EinsteinVisionQueueble implements Queueable, Database.AllowsCallouts{

    private Einstein_Vision_Dataset__c dataset{get;Set;}
   
    public EinsteinVisionQueueble(Einstein_Vision_Dataset__c dataset){
        this.dataset = dataset;
    }
    
    public void execute(QueueableContext context) {
        list<Error_Log__c> lsterrorlogs = new list<Error_Log__c>();
        String datasetId ;
        String modelId ;
        //Create a new Instance of Dataset record
        Einstein_Vision_Dataset__c datasetToUpdate = new Einstein_Vision_Dataset__c();
        datasetToUpdate.Id = dataset.id;
        //Initiate the Creation Of Dataset Call
        try{
            EinsteinVisionDatasetResult einsteinResult = EinstieinVisionCreateDatasetUtil.createDatasetFromURLAsync(dataset.Public_URL__c,false);
            datasetId = String.valueof(einsteinResult.id);
            datasetToUpdate.DatasetId__c = datasetId;
        }catch(exception ex){
           lsterrorlogs.add(logError('DATASET CREATION',ex.getMessage(),dataset.id));
           return ;
        }
        //Check the Status of the Creation of dataset
        if(datasetId !=null){
            boolean statusSucceedorFail = false ;
            while(!statusSucceedorFail){
                EinsteinVisionDatasetResult einsteinResult = EinsteinVisionGetDataset.getDataSetStatus(datasetId,false);
                if(einsteinResult.statusMsg == 'SUCCEEDED'){
                   statusSucceedorFail = true;
                   datasetToUpdate.Status__c = einsteinResult.statusMsg;
                }else if(einsteinResult.statusMsg == 'FAILED'){
                    lsterrorlogs.add(logError('DATASET CREATION','FAILED',dataset.Id));
                    statusSucceedorFail = true;
                    datasetToUpdate.Status__c = einsteinResult.statusMsg;
                    return ;
                }else{
                    Integer start = System.Now().millisecond();
                    while(System.Now().millisecond()< start+30000){ 
                    }
                    system.debug('Data Creation is Running with Status '+einsteinResult.statusMsg);
                }
            }
        }
        //train the Dataset
        try{
            EinsteinVisionTrainDataSetResponse response = EinsteinVisionTrainDataset.trainDataSet(dataset.name,datasetId,false);
            modelId = response.modelId;
            datasetToUpdate.ModelId__c = modelId;
        }catch(exception e){
           lsterrorlogs.add(logError('TRAINING',e.getMessage(),dataset.id));
           return ;
        }
        //Poll for the response until job succeeds or fails 
        if(modelId !=null){
            boolean statusTrainingSucceedorFail = false ;
            while(!statusTrainingSucceedorFail){
                EinsteinVisionTrainDataSetResponse einsteinTrainingResult = EinsteinVisionTrainDataset.gettrainingStatus(modelId,false);
                if(einsteinTrainingResult.status == 'SUCCEEDED'){
                   statusTrainingSucceedorFail = true;
                   datasetToUpdate.Training_Status__c = einsteinTrainingResult.status;
                }else if(einsteinTrainingResult.status == 'FAILED'){
                    lsterrorlogs.add(logError('TRAINING','FAILED',dataset.Id));
                    statusTrainingSucceedorFail = true;
                    datasetToUpdate.Training_Status__c = einsteinTrainingResult.status;
                     return ;
                }else{
                    Integer start = System.Now().millisecond();
                    while(System.Now().millisecond()< start+30000){ 
                    }
                    system.debug('Data Creation is Running with Status '+einsteinTrainingResult.status);
                }
            }
        }
        //Update the dataset
        update dataset;
    }

    private static Error_Log__c logError(String jobtype,String errormessage,Id datasetId){
         Error_Log__c error = new Error_Log__c();
         error.Job_Type__c = jobtype;
         error.Error_Message__c = errormessage;
         error.Einstein_Vision_Dataset__c = datasetId;
         return error;
    }

}